"""
Narzedzia CSS dla CrewAI IdoBooking.
Generowanie design tokenow, walidacja kontrastu WCAG.
"""

import re
from crewai.tools import tool


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Konwertuj hex na RGB."""
    hex_color = hex_color.lstrip("#")
    if len(hex_color) == 3:
        hex_color = "".join(c * 2 for c in hex_color)
    return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))


def relative_luminance(r: int, g: int, b: int) -> float:
    """Oblicz luminancje wzgledna wg WCAG 2.1."""
    def linearize(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * linearize(r) + 0.7152 * linearize(g) + 0.0722 * linearize(b)


def contrast_ratio(color1: str, color2: str) -> float:
    """Oblicz wspolczynnik kontrastu miedzy dwoma kolorami hex."""
    l1 = relative_luminance(*hex_to_rgb(color1))
    l2 = relative_luminance(*hex_to_rgb(color2))
    lighter = max(l1, l2)
    darker = min(l1, l2)
    return (lighter + 0.05) / (darker + 0.05)


@tool("check_contrast")
def check_contrast(foreground: str, background: str) -> str:
    """
    Sprawdz kontrast WCAG miedzy kolorem tekstu i tla.
    Podaj kolory w formacie hex (#RRGGBB).
    Zwraca: ratio, AA normal, AA large, AAA normal, AAA large.
    """
    try:
        ratio = contrast_ratio(foreground, background)
    except (ValueError, IndexError):
        return f"BLAD: Nieprawidlowy format koloru. Uzyj #RRGGBB."

    aa_normal = "PASS" if ratio >= 4.5 else "FAIL"
    aa_large = "PASS" if ratio >= 3.0 else "FAIL"
    aaa_normal = "PASS" if ratio >= 7.0 else "FAIL"
    aaa_large = "PASS" if ratio >= 4.5 else "FAIL"

    return (
        f"Kontrast {foreground} na {background}: {ratio:.2f}:1\n"
        f"  AA normal text (4.5:1): {aa_normal}\n"
        f"  AA large text  (3.0:1): {aa_large}\n"
        f"  AAA normal text (7.0:1): {aaa_normal}\n"
        f"  AAA large text  (4.5:1): {aaa_large}"
    )


@tool("generate_css_tokens")
def generate_css_tokens(
    prefix: str,
    brand: str,
    bg: str,
    text: str,
    accent: str = "",
) -> str:
    """
    Generuj bazowe design tokeny CSS dla projektu IdoBooking.
    Podaj: prefix (np. md), brand (#hex), bg (#hex), text (#hex).
    Opcjonalnie: accent (#hex).
    """
    if not accent:
        # Uzyj brand jako accent
        accent = brand

    # Oblicz warianty
    brand_rgb = hex_to_rgb(brand)
    bg_rgb = hex_to_rgb(bg)
    text_rgb = hex_to_rgb(text)

    # Muted bg (mieszanka bg + text 8%)
    muted_r = int(bg_rgb[0] * 0.92 + text_rgb[0] * 0.08)
    muted_g = int(bg_rgb[1] * 0.92 + text_rgb[1] * 0.08)
    muted_b = int(bg_rgb[2] * 0.92 + text_rgb[2] * 0.08)
    bg_muted = f"#{muted_r:02X}{muted_g:02X}{muted_b:02X}"

    # Alt bg (mieszanka bg + text 4%)
    alt_r = int(bg_rgb[0] * 0.96 + text_rgb[0] * 0.04)
    alt_g = int(bg_rgb[1] * 0.96 + text_rgb[1] * 0.04)
    alt_b = int(bg_rgb[2] * 0.96 + text_rgb[2] * 0.04)
    bg_alt = f"#{alt_r:02X}{alt_g:02X}{alt_b:02X}"

    # Text muted (mieszanka text + bg 40%)
    tm_r = int(text_rgb[0] * 0.6 + bg_rgb[0] * 0.4)
    tm_g = int(text_rgb[1] * 0.6 + bg_rgb[1] * 0.4)
    tm_b = int(text_rgb[2] * 0.6 + bg_rgb[2] * 0.4)
    text_muted = f"#{tm_r:02X}{tm_g:02X}{tm_b:02X}"

    # Text subtle (mieszanka text + bg 55%)
    ts_r = int(text_rgb[0] * 0.45 + bg_rgb[0] * 0.55)
    ts_g = int(text_rgb[1] * 0.45 + bg_rgb[1] * 0.55)
    ts_b = int(text_rgb[2] * 0.45 + bg_rgb[2] * 0.55)
    text_subtle = f"#{ts_r:02X}{ts_g:02X}{ts_b:02X}"

    # Brand hover (darker)
    bh_r = max(0, int(brand_rgb[0] * 0.8))
    bh_g = max(0, int(brand_rgb[1] * 0.8))
    bh_b = max(0, int(brand_rgb[2] * 0.8))
    brand_hover = f"#{bh_r:02X}{bh_g:02X}{bh_b:02X}"

    css = f"""/* ============================================================
   Design Tokens: {prefix}
   Generated by CrewAI IdoBooking
   ============================================================ */

:root {{
    /* --- Marka --- */
    --{prefix}-brand:        {brand};
    --{prefix}-brand-hover:  {brand_hover};
    --{prefix}-accent:       {accent};

    /* --- Tla --- */
    --{prefix}-bg:           {bg};
    --{prefix}-bg-alt:       {bg_alt};
    --{prefix}-bg-muted:     {bg_muted};
    --{prefix}-bg-card:      #FFFFFF;
    --{prefix}-bg-light:     {bg};

    /* --- Tekst --- */
    --{prefix}-text:         {text};
    --{prefix}-text-muted:   {text_muted};
    --{prefix}-text-subtle:  {text_subtle};

    /* --- Obramowania --- */
    --{prefix}-border:       rgba({text_rgb[0]},{text_rgb[1]},{text_rgb[2]},0.2);
    --{prefix}-border-light: rgba({text_rgb[0]},{text_rgb[1]},{text_rgb[2]},0.35);
    --{prefix}-border-muted: rgba({text_rgb[0]},{text_rgb[1]},{text_rgb[2]},0.12);

    /* --- Typografia --- */
    --{prefix}-font:         'Inter', system-ui, -apple-system, sans-serif;
    --{prefix}-font-heading:  var(--{prefix}-font);
    --{prefix}-leading:       1.7;
    --{prefix}-leading-tight: 1.15;

    /* --- Layout --- */
    --{prefix}-max-w:        1100px;
    --{prefix}-gap:          clamp(24px, 4vw, 48px);
    --{prefix}-radius:       6px;

    /* --- Animacje --- */
    --{prefix}-transition:   0.25s ease;
}}
"""

    # Sprawdz kontrast
    main_contrast = contrast_ratio(text, bg)
    brand_on_bg = contrast_ratio(brand, bg)
    brand_on_text = contrast_ratio(brand, text)

    css += f"""
/* Kontrast WCAG:
   text/bg:     {main_contrast:.2f}:1 {"PASS" if main_contrast >= 4.5 else "FAIL"} AA
   brand/bg:    {brand_on_bg:.2f}:1 {"PASS" if brand_on_bg >= 3.0 else "FAIL"} AA-large
   brand/text:  {brand_on_text:.2f}:1
*/
"""

    return css


@tool("audit_css_contrast")
def audit_css_contrast(css_content: str) -> str:
    """
    Audytuj plik CSS pod katem kontrastu kolorow.
    Znajdz pary color/background i sprawdz WCAG AA.
    """
    # Wyciagnij zmienne z :root
    variables = {}
    root_match = re.search(r":root\s*\{([^}]+)\}", css_content, re.DOTALL)
    if root_match:
        for line in root_match.group(1).split("\n"):
            m = re.match(r"\s*--([\w-]+)\s*:\s*(#[0-9A-Fa-f]{3,8})", line)
            if m:
                variables[f"--{m.group(1)}"] = m.group(2)

    if not variables:
        return "Brak zmiennych CSS z kolorami hex w :root"

    # Sprawdz typowe pary
    issues = []
    checks = []

    prefix = ""
    for var in variables:
        if "-brand" in var:
            prefix = var.split("-brand")[0].lstrip("-")
            break

    pairs_to_check = [
        ("text", "bg", "Tekst na tle glownym"),
        ("text", "bg-muted", "Tekst na tle muted"),
        ("text-muted", "bg", "Tekst muted na tle glownym"),
        ("brand", "bg", "Brand na tle glownym"),
    ]

    for fg_suffix, bg_suffix, desc in pairs_to_check:
        fg_var = f"--{prefix}-{fg_suffix}"
        bg_var = f"--{prefix}-{bg_suffix}"
        if fg_var in variables and bg_var in variables:
            ratio = contrast_ratio(variables[fg_var], variables[bg_var])
            status = "PASS" if ratio >= 4.5 else "FAIL"
            if status == "FAIL":
                issues.append(f"  FAIL: {desc}: {ratio:.2f}:1 ({variables[fg_var]} na {variables[bg_var]})")
            checks.append(f"  {status}: {desc}: {ratio:.2f}:1")

    result = f"Audit kontrastu ({len(checks)} par sprawdzonych):\n"
    result += "\n".join(checks)
    if issues:
        result += f"\n\nPROBLEMY ({len(issues)}):\n" + "\n".join(issues)
    else:
        result += "\n\nWszystkie pary PASS WCAG AA."

    return result
